### AI模型配置
### 修改后即时生效，无需重启

# 阿里巴巴千问模型api key
qianwen.api_key=

# DeepSeek api key
ds.api.key=

# DeepSeek api baseurl
ds.api.base_url=https://api.deepseek.com

# DeepSeek 请求超时时长，单位秒
ds.api.timeout=30
