### B站相关配置

# b站cookie中的SESSDATA，用于解析b站视频等需要调用b站api的功能
bilibili.cookies.sessdata=

# b站cookie中的bili_jct，用于解析b站视频等需要调用b站api的功能
bilibili.cookies.bili_jct=

# 请求b站接口自动获取，非必要，可减小风控概率（由程序自动写入）
bilibili.cookies.ticket=

# 上传b站视频时长限制，单位秒
bilibili.upload_video.duration_limit=600

# 下载b站视频时长限制，单位秒
bilibili.download_video.duration_limit=600
