### 机器人自身行为配置

# qq客户端是否与本服务在同一台机器
# true：图片/语音使用 file:// 本地路径发送；false：使用下面的对外地址拼接http url
bot.same-machine-qqclient=true

# 机器人超级管理员qq号，多个用逗号分割
bot.superusers=1527188922

# 可使用机器人的群号，多个用逗号分开
# 留空表示所有群都可使用机器人
bot.access_groups=

# 上传私聊/群文件时是否并发发送请求
# true：并发发送；false：排队发送
bot.upload_file.parallel=true

# 是否禁用所有群功能（对所有群消息不予理睬，但保留保存聊天记录功能）
bot.switch.disable_group=false

# 是否启用青云可聊天api（at机器人或私聊机器人任何命令都未触发时会调用）
bot.switch.qingyunke_chat=true

# 是否允许群聊中使用识图功能
bot.switch.search_image_allow_group=true

# 是否允许群聊中使用bt搜索功能
bot.switch.search_bt_allow_group=true

# 是否开启加群提示
bot.switch.group_increase=true

# 是否开启群成员离群提示
bot.switch.group_decrease=true
