### 识图 / 图源站点配置
### 修改后即时生效

# saucenao 识图接口地址
searchimg.saucenao.baseurl=https://saucenao.com/search.php

# saucenao 识图接口认证key，从 https://saucenao.com 获取，留空则以匿名方式请求
searchimg.saucenao.apikey=

# agefans网站地址，用于今日新番功能，末尾不需斜杠
# 备用：https://www.age.tv  https://www.agemys.net  https://www.agemys.cc
searchimg.agefans.url=https://www.agemys.vip
