### 第三方站点地址
### 末尾不需斜杠

# 磁力搜索网站地址，用于bt搜索功能
# 备用：http://www.eclzz.art  http://www.eclzz.win  http://www.eclzz.love
url_conf.bt_search=http://www.eclzz.bio

# bt影视搜索站点地址
url_conf.btbtla_search=https://www.btbtla.com
