### 第三方站点与接口地址
### 大多数末尾不需斜杠，修改后即时生效
###
### 说明：识图接口（saucenao）的地址与key在 searchimg.properties 里

# agefans网站地址，用于今日新番功能
# 备用：https://www.age.tv  https://www.agemys.net  https://www.agemys.cc
url_conf.agefans=https://www.agemys.vip

# 磁力搜索网站地址，用于bt搜索功能
# 备用：http://www.eclzz.art  http://www.eclzz.win  http://www.eclzz.love
url_conf.bt_search=http://www.eclzz.bio

# bt影视搜索站点地址
url_conf.btbtla_search=https://www.btbtla.com

# 青云客ai聊天接口
url_conf.qingyunke_ai_chat=http://api.qingyunke.com/api.php

# b站获取弹幕接口
url_conf.bilibili_bullet_char=https://api.bilibili.com/x/v1/dm/list.so

# b站获取cid接口
url_conf.bilibili_player_cid=https://api.bilibili.com/x/player/pagelist

# b站根据uid批量获取直播间状态接口
url_conf.bilibili_live_status=https://api.live.bilibili.com/room/v1/Room/get_status_info_by_uids

# lolicon图片接口，用于pixiv下载任务
url_conf.lolicon=https://api.lolicon.app/setu/v2

# 磁力链接预览接口
url_conf.whats_link=https://whatslink.info/api/v1/link

# 网易新闻头条接口
url_conf.news_163=http://c.m.163.com/nc/article/headline/T1348647853363/0-40.html

# 网易云搜索歌曲接口
url_conf.netease_search_music=http://music.163.com/weapi/cloudsearch/get/web
