login.username=haruhi
login.password=123123

# JWT有效时长 单位小时
login.jwt.expire=24

# JWT secret
login.jwt.secret=QBgu5c4xfA4_6Ky8A_QnO_XW238-YD7Y6EH7HQKAyM8OiCNbn6xCcN-5BaZGysxA

# 内存中token最大数量
login.session.max=6

# 目前无用
login.jwt.grace=30
# 内存token过期时长
login.expire=30