login.username=haruhi
login.password=123456

# JWT ????????????
login.jwt.expire=24

# JWT ?????????????? 32 ???????
login.jwt.secret=QBgu5c4xfA4_6Ky8A_QnO_XW238-YD7Y6EH7HQKAyM8OiCNbn6xCcN-5BaZGysxA

# ????????? token ??
login.session.max=6

# ???JWT ???????????(????)
login.jwt.grace=30
# ??????????????
login.expire=30