env:
  active: dev
bot:
  name: 春日酱
  port: 8090
  enable-internet-host: 0
  internet-host:
  same-machine-qqclient: true

job:
  downloadPixiv:
    cron: 0/15 * 0-7 * * ? *
    enable: 1

server:
  port: ${bot.port}

mybatis-plus:
  type-aliases-package: com.haruhi.botServer.entity
  mapper-locations: classpath:/mapper/**/*.xml

logging:
  level:
    com.haruhi.botServer: debug

log:
  level: info
  path: logs
  filename: haruhibot

spring:
  application:
    name: haruhi-bot-service
