env:
  active: dev
bot:
  name: 春日酱
  port: 8090
  enable-internet-host: 0
  internet-host:
  default-user: 1234567890
  same-machine-qqclient: true

job:
  downloadPixiv:
    cron: 0/15 * 0-7 * * ? *
    enable: 1
    
url-conf:
  agefans: https://www.agemys.vip
  bt-search: http://www.eclzz.bio

switch:
  ai-chat: 1
  search-image-allow-group: 1
  group-decrease: 1
  group-increase: 1
  search-bt-allow-group: 1
  disableGroup: 0

server:
  port: ${bot.port}

mybatis-plus:
  type-aliases-package: com.haruhi.botServer.entity
  mapper-locations: classpath:/mapper/**/*.xml

logging:
  level:
    com.haruhi.botServer: debug

log:
  level: info
  path: logs
  filename: haruhibot

spring:
  application:
    name: haruhi-bot-service
