env:
  active: dev
bot:
  name: 春日酱
  port: 8090
  enable-internet-host: 0
  internet-host:
  search-image-key:
  access-token: haruhi123
  default-user: 1234567890
  superusers: 1527188922,1234567890
  max-connections: 5

chatgpt:
  email:
  password:
  session-token:
  cf-clearance:
  user-agent:

mysql:
  host: 127.0.0.1
  port: 3306
  dbName: haruhibot_server
  username: root
  password: yto123456

job:
  downloadPixiv:
    cron: 0/15 * 0-7 * * ? *
    enable: 1
    
url-conf:
  agefans: https://www.agemys.vip
  bt-search: http://www.eclzz.bio

switch:
  ai-chat: 1
  search-image-allow-group: 1
  group-decrease: 1
  group-increase: 1
  search-bt-allow-group: 1
  disableGroup: 0
    

server:
  port: ${bot.port}
  servlet:
    context-path: /haruhi
    ws-path: /ws1222

mybatis-plus:
  type-aliases-package: com.haruhi.botServer.entity
  mapper-locations: classpath:/mapper/**/*.xml

logging:
  level:
    com.haruhi.botServer: debug

log:
  level: info
  path: logs
  filename: haruhibot

spring:
  datasource:
    dynamic:
      datasource:
        master:
          dbName: mysql
          username: ${mysql.username}
          password: ${mysql.password}
          url: jdbc:mysql://${mysql.host}:${mysql.port}/${spring.datasource.dynamic.datasource.master.dbName}?useUnicode=true&characterEncoding=utf-8&useSSL=false
          driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: haruhi-bot-service
