env:
  active: dev

server:
  port: 8090

bot:
  internet-host:
  same-machine-qqclient: true

job:
  downloadPixiv:
    cron: 0/15 * 0-7 * * ? *
    enable: 1


mybatis-plus:
  type-aliases-package: com.haruhi.botServer.entity

logging:
  level:
    com.haruhi.botServer: debug

#spring:
#  datasource:
#    dynamic:
#      datasource:
#        master:
#          url: jdbc:sqlite:D:\my\bot\db\haruhibot_server.db
#          driver-class-name: org.sqlite.JDBC
#          druid:
#            validation-query: SELECT 1
#            filters: stat
#            test-on-borrow: false
#            test-on-return: false
#            pool-prepared-statements: false
#            max-active: 1